# # # version: "3.8"
# # services:
# #   pg:
# #     image: postgres:15-amd64
# #     platform: linux/amd64         # GHIM kiến trúc
# #     container_name: htvb_test_pg
# #     environment:
# #       POSTGRES_USER: postgres
# #       POSTGRES_PASSWORD: postgres
# #       POSTGRES_DB: htvb
# #     ports:
# #       - "5432:5432"
# #     healthcheck:
# #       test: ["CMD-SHELL", "pg_isready -U postgres -d htvb || exit 1"]
# #       interval: 2s
# #       timeout: 3s
# #       retries: 20
# #     restart: unless-stopped
# #     shm_size: "256m"

# services:
#   pg:
#     image: postgres:15
#     platform: linux/amd64            # GHIM amd64 để không kéo nhầm ARM
#     container_name: htvb_test_pg
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: htvb
#       LANG: C.UTF-8
#       LC_ALL: C.UTF-8
#       TZ: UTC
#     ports:
#       - "5432:5432"                 # tránh va 5432
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d htvb || exit 1"]
#       interval: 2s
#       timeout: 3s
#       retries: 20
#     restart: unless-stopped
#     shm_size: "256m"
#     pull_policy: always              # ép Compose kéo lại image đúng


# services:
#   pg:
#     image: postgres:15-alpine
#     platform: linux/amd64
#     container_name: htvb_test_pg
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: htvb
#       LANG: C.UTF-8
#       LC_ALL: C.UTF-8
#       TZ: UTC
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d htvb || exit 1"]
#       interval: 2s
#       timeout: 3s
#       retries: 20
#     restart: unless-stopped
#     shm_size: "256m"
#     pull_policy: always

services:
  pg:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: htvb_test_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: htvb
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: UTC
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d htvb || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    shm_size: "256m"
    pull_policy: always
